// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const VITE_SUPABASE_URL = "https://goomvvzrfhjuuvxznmht.supabase.co";
const VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvb212dnpyZmhqdXV2eHpubWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjIzOTgsImV4cCI6MjA2NTIzODM5OH0.Ts094BYgv_28iudSdmGWNsKChycKQcZverQz0n_tfdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY);